# Docker Compose configuration for Ithaka development environment
# This file defines the PostgreSQL database service

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ithaka-postgres
    restart: unless-stopped

    # Environment variables (matches backend/.env)
    environment:
      POSTGRES_USER: ithaka_user
      POSTGRES_PASSWORD: ithaka_password
      POSTGRES_DB: ithaka_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"

    # Port mapping (host:container)
    ports:
      - "5432:5432"

    # Persistent data volume
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optional: mount init scripts
      # - ./backend/db/init:/docker-entrypoint-initdb.d

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ithaka_user -d ithaka_db"]
      interval: 10s
      timeout: 5s
      retries: 5

    # Network
    networks:
      - ithaka-network

# Named volumes for data persistence
volumes:
  postgres_data:
    driver: local

# Network for inter-container communication
networks:
  ithaka-network:
    driver: bridge

# Usage:
# - Start services:     docker-compose up -d
# - Stop services:      docker-compose down
# - View logs:          docker-compose logs -f postgres
# - Access PostgreSQL:  docker exec -it ithaka-postgres psql -U ithaka_user -d ithaka_db
# - Reset data:         docker-compose down -v (CAUTION: deletes all data)
